version: '3.9'

services:

  local:
    stdin_open: true
    tty: true
    image: sadtalker:v1.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./:/workspace
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
